params:
  model: resnet50
  batch_size: 32
  learning_rate: 0.001
  training_epoch: 25
  img_size: 224
  no_gpu: 2

data:
  data_dir: /workspaces/chexpert/data/raw/
  raw:
    train: /workspaces/chexpert/data/raw/CheXpert-v1.0-small/train.csv
    test: /workspaces/chexpert/data/raw/CheXpert-v1.0-small/valid.csv
  processed:
    train: /workspaces/chexpert/data/processed/train.csv
    val: /workspaces/chexpert/data/processed/val.csv
    test: /workspaces/chexpert/data/processed/test.csv


model:
  save: "/workspaces/chexpert/models/covid.h5"
